import 'infos.dart';

final List<Map<String, dynamic>> pillList = [
  {
    'inf': inf[1],
    'id': 1,
    'img': 'images/1.png',
    'name': 'ЦИНЕПАР',
    'price': 32.00,
  },
  {
    'inf': inf[2],
    'id': 2,
    'img': 'images/2.png',
    'name': 'Доктор МОМ',
    'price': 72.00,
  },
  {
    'inf': inf[3],
    'id': 3,
    'img': 'images/3.png',
    'name': 'Миг-400',
    'price': 33.00,
  },
  {
    'inf': inf[4],
    'id': 4,
    'img': 'images/4.png',
    'name': 'Evavit',
    'price': 77.00,
  },
  {
    'inf': inf[5],
    'id': 5,
    'img': 'images/5.png',
    'name': 'Тримол',
    'price': 12.00,
  },
  {
    'inf': inf[6],
    'id': 6,
    'img': 'images/6.png',
    'name': 'Дексалгин',
    'price': 112.00,
  },
  {
    'inf': inf[7],
    'id': 7,
    'img': 'images/7.png',
    'name': 'Медизин',
    'price': 24.00,
  },
  {
    'inf': inf[8],
    'id': 8,
    'img': 'images/8.png',
    'name': 'Корвалол ',
    'price': 15.00,
  },
  {
    'inf': inf[9],
    'id': 9,
    'img': 'images/9.png',
    'name': 'АКБАР (AKBAR)',
    'price': 8.00,
  },
  {
    'inf': inf[10],
    'id': 10,
    'img': 'images/10.png',
    'name': 'Ламбротин',
    'price': 30.00,
  },
  {
    'inf': inf[11],
    'id': 11,
    'img': 'images/11.png',
    'name': 'Эритромициновая',
    'price': 18.00,
  },
  {
    'inf': inf[12],
    'id': 12,
    'img': 'images/12.png',
    'name': 'Энап НЛ 20',
    'price': 57.00,
  },
  {
    'inf': inf[13],
    'id': 13,
    'img': 'images/13.png',
    'name': 'Эрфлюсал',
    'price': 650.00,
  },
  {
    'inf': inf[14],
    'id': 14,
    'img': 'images/14.png',
    'name': 'Берлиприл 20 mg',
    'price': 102.00,
  },
  {
    'inf': inf[15],
    'id': 15,
    'img': 'images/15.png',
    'name': 'Бейби калм',
    'price': 102.00,
  },
  {
    'inf': inf[16],
    'id': 16,
    'img': 'images/16.png',
    'name': 'БОБЕНАК-П ',
    'price': 10.00,
  },
  {
    'inf': inf[17],
    'id': 17,
    'img': 'images/17.png',
    'name': 'Квамател',
    'price': 61.00,
  },
  {
    'inf': inf[18],
    'id': 18,
    'img': 'images/18.png',
    'name': 'Боро плюс',
    'price': 5.00,
  },
  //!   New  Pills
  {
    'inf': inf[19],
    'id': 19,
    'img': 'images/19.png',
    'name': 'ДентаБаланс',
    'price': 54.00,
  },
  {
    'inf': inf[20],
    'id': 20,
    'img': 'images/20.png',
    'name': 'Фастум гель',
    'price': 32.00,
  },
  {
    'inf': inf[21],
    'id': 21,
    'img': 'images/21.png',
    'name': 'Фестал',
    'price': 24.00,
  },
  {
    'inf': inf[22],
    'id': 22,
    'img': 'images/22.png',
    'name': 'Бетасерк Лонг',
    'price': 176.00,
  },
  {
    'inf': inf[23],
    'id': 23,
    'img': 'images/23.png',
    'name': 'Азитромицин',
    'price': 22.00,
  },
  {
    'inf': inf[24],
    'id': 24,
    'img': 'images/24.png',
    'name': 'Лютеин-комплекс',
    'price': 53.00,
  },
  {
    'inf': inf[25],
    'id': 25,
    'img': 'images/25.png',
    'name': 'Орлит',
    'price': 60.00,
  },
  {
    'inf': inf[26],
    'id': 26,
    'img': 'images/26.png',
    'name': 'Капсикам',
    'price': 21.00,
  },
  {
    'inf': inf[27],
    'id': 27,
    'img': 'images/27.png',
    'name': 'Но-шпа',
    'price': 18.00,
  },
  {
    'inf': inf[28],
    'id': 28,
    'img': 'images/28.png',
    'name': 'Алмагель',
    'price': 26.00,
  },
  {
    'inf': inf[29],
    'id': 29,
    'img': 'images/29.png',
    'name': 'Мезим форте',
    'price': 18.00,
  },
  {
    'inf': inf[30],
    'id': 30,
    'img': 'images/30.png',
    'name': 'Эспумизан',
    'price': 24.00,
  },
  {
    'inf': inf[31],
    'id': 31,
    'img': 'images/31.png',
    'name': 'ДентоБЛИС',
    'price': 78.00,
  },
  {
    'inf': inf[32],
    'id': 32,
    'img': 'images/32.png',
    'name': 'Тантум Верде',
    'price': 21.00,
  },
  {
    'inf': inf[33],
    'id': 33,
    'img': 'images/33.png',
    'name': 'Линекс Форте',
    'price': 21.00,
  },
  {
    'inf': inf[34],
    'id': 34,
    'img': 'images/34.png',
    'name': 'Гевискон',
    'price': 21.00,
  },
  {
    'inf': inf[35],
    'id': 35,
    'img': 'images/35.png',
    'name': 'Метоклопрамид',
    'price': 21.00,
  },
  {
    'inf': inf[36],
    'id': 36,
    'img': 'images/36.png',
    'name': 'Тимоген',
    'price': 21.00,
  },
  {
    'inf': inf[37],
    'id': 37,
    'img': 'images/37.png',
    'name': 'Орвис Иммуно',
    'price': 21.00,
  },
  {
    'inf': inf[38],
    'id': 38,
    'img': 'images/38.png',
    'name': 'Экорал',
    'price': 21.00,
  },
  {
    'inf': inf[39],
    'id': 39,
    'img': 'images/39.png',
    'name': 'Алмагель',
    'price': 21.00,
  },
  {
    'inf': inf[40],
    'id': 40,
    'img': 'images/40.png',
    'name': 'Нурофен ',
    'price': 21.00,
  },
  {
    'inf': inf[41],
    'id': 41,
    'img': 'images/41.png',
    'name': 'Юниспаз Н',
    'price': 21.00,
  },
  {
    'inf': inf[42],
    'id': 42,
    'img': 'images/42.png',
    'name': 'Аспирин Экспресс',
    'price': 21.00,
  },
  {
    'inf': inf[43],
    'id': 43,
    'img': 'images/43.png',
    'name': 'Велдексал',
    'price': 21.00,
  },
  {
    'inf': inf[44],
    'id': 44,
    'img': 'images/44.png',
    'name': 'Тизин Алерджи',
    'price': 21.00,
  },
  {
    'inf': inf[45],
    'id': 45,
    'img': 'images/45.png',
    'name': 'Кларитин',
    'price': 21.00,
  },
  {
    'inf': inf[46],
    'id': 46,
    'img': 'images/46.png',
    'name': 'Нурофаст',
    'price': 21.00,
  },
  {
    'inf': inf[47],
    'id': 47,
    'img': 'images/47.png',
    'name': 'Арбидол Максимум',
    'price': 21.00,
  },
  {
    'inf': inf[48],
    'id': 48,
    'img': 'images/48.png',
    'name': 'АЦЦ 200',
    'price': 21.00,
  },
  {
    'inf': inf[49],
    'id': 49,
    'img': 'images/49.png',
    'name': 'Виброцил',
    'price': 21.00,
  },
  {
    'inf': inf[50],
    'id': 50,
    'img': 'images/50.png',
    'name': 'Тилорон ',
    'price': 21.00,
  },
];
